TARGET = libftp
TYPE = so
LIB_INCLUDE = ftp.h
EXTRA_CFLAGS = $(type_compat_cflags)
EXTRA_LDFLAGS = -lcurl $(type_compat_ldflags)                                                                                                                                                                                                                                   
SOURCE = $(wildcard *.c)

include $(TOPDIR)/common.mk
